version: '3'
services:
  decidim:
    build: '.'
    entrypoint: /bin/sh -c
    command: bundle exec rake development_app
    working_dir: /code
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
      - tmp:/code/development_app/tmp
      - assets:/code/development_app/public/assets
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    ports:
      - 3000:3000
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  bundle: {}
  tmp: {}
  assets: {}
  pg-data: {}
  redis-data: {}
