version: '3'
services:
  decidim:
    build: '.'
    command: bundle exec rake development_app
    working_dir: /code
    volumes:
      - .:/code
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    ports:
      - 3000:3000
    links:
      - pg
      - redis
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: redis
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
